### ISSUE TITLE
Copyright attribution

### ISSUE THREAD

**Issue by dominikh** [paetzke/buftra.el#1]
Large parts of buftra.el are copied from [go-mode](https://github.com/dominikh/go-mode.el), with only slight changes. As per the [license of go-mode](https://github.com/dominikh/go-mode.el/blob/master/LICENSE), you should retain the original copyright notice and license text applying to the copied code. Thanks!

**Comment by paetzke** [comment]
You are absolutely right. If you would review this [patch](https://github.com/paetzke/buftra.el/compare/rectify-copyright?expand=1) I am more than happy to merge it. Sorry that I have missed this.

**Comment by dominikh** [comment]
That'll do, thanks. I'd probably rephrase

> This code is initially copied from go-mode.el.

as

> This code is initially copied from go-mode.el (copyright the go-mode authors).

That'd work best with buftra being embedded in your other projects and wouldn't conflict with the copyright/author info at the top of the file.

Apart from that it's more than satisfactory, thank you :)

**Comment by paetzke** [comment]
It's merged.
